# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  	desc "Description of what the lane does"
  	lane :custom_lane do
    	# add actions here: https://docs.fastlane.tools/actions
  	end

  	desc "Does a static analysis of the project. Configure the options in .swiftlint.yml"
  	lane :lint do
    	swiftlint(
	  		mode: :lint,
			executable: "Pods/SwiftLint/swiftlint",
			reporter: "html",
			output_file: "fastlane/swiftlint-results.html",
			config_file: '.swiftlint.yml',
			ignore_exit_status: true
		)
	end

	desc "Test an measure code coverage"
	lane :test do
		run_tests(devices: ["iPhone 11"])
		xcov(
			workspace: "IIEventCalendar.xcworkspace",
			scheme: "IIEventCalendar",
			output_directory: "fastlane/xcov_output"
		)
	end

	lane :release_pod do |options|
		target_repo    = options[:repo]
		target_project = options[:project]
		target_version = options[:version]
		spec_path = "../#{target_project}.podspec"

		# 确认是 master 分支
		ensure_git_branch
		# 修改 spec 为即将发布的版本
		version_bump_podspec(path: spec_path, version_number: target_version)
		# 提交代码到远程仓库
		git_commit(path: spec_path, message: 'release')
		push_to_git_remote
		# 检查对于 tag 是否已经存在
		if git_tag_exists(tag: target_version)
			# 删除对应 tag
			remove_git_tag(tag: target_version)
		end
		# 添加 tag
		add_git_tag(tag: target_version)
		# 提交 tag
		push_git_tags
		# 验证 spec 文件
		pod_lib_lint(allow_warnings: true)
		# 检查是否传了 repo 参数
		if target_repo
			# pod repo push 'target_repo' 'spec_path'
			pod_push(path: spec_path, repo: target_repo, allow_warnings: true)
		else
		# pod trunk push 'spec_path'
		pod_push(path: spec_path, allow_warnings: true)
		end
	end
end
