# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate-and-test:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test Example Project
        run: |
          cd Example
          pwd
          bundle install
          bundle exec pod install
          bundle exec fastlane lint
          bundle exec fastlane test

      - name: Checkout master
        uses: actions/checkout@master

      - name: Publish To trunk
        run: |
          cd Example
          pwd
          bundle install
          bundle exec fastlane release_pod project:'IIEventCalendar' version:'0.9.3'
